### ISSUE TITLE
Persistent HD

### ISSUE THREAD

**Issue by rossimariolee** [dirkwhoffmann/vAmiga#670] opened 2022-03-23 08:29 UTC
Hi, is it possible to have recognized the kickstart 1.3 (rev 34.005) that has the HD device drivers in to boot from HD directly ?

Kickstart - 315093-02 (USA, Europe) (v1.3 Rev 34.005) (A500, A2000).zip

Booting from Winuae -
![Untitled 2](https://user-images.githubusercontent.com/41687618/159656709-d056a74c-5a43-4cea-9764-5171af21bf94.png)

**Comment by Alvarez81** [comment] 2022-03-23 09:32
A Kickstart 1.3 + SCSI.device made for fisrt Amiga 3000 and last A2000 models. 
Well, got it, I do not like Workbench >= 2.0 
Never tried before, even if I know that  there were some kickstarts with SCSI\IDE drivers patched or builted in for A3000-A2500 (Janus XT-AT-386).

**Comment by Alessandro1970** [comment] 2022-03-23 10:51
I don't succeed in formatting the Hard Drive with this kind of kickstart.
I only succeed in with Kick 2.05 (Amiga 600HD or higher).

Is this a patched Kick ? (http://aminet.net/package/util/boot/kick13scsipatch)
Let me know about.

**Comment by Alessandro1970** [comment] 2022-03-23 11:48
I can boot from Hard Drive Image (60Mb Disco) with kickstart 3.1.4

![jpg](https://user-images.githubusercontent.com/34916641/159692313-a3acb4d6-b7ad-4bf5-97ef-172625e9f788.png)

**Comment by dirkwhoffmann** [comment] 2022-03-23 14:30
> Kickstart - 315093-02 (USA, Europe) (v1.3 Rev 34.005) (A500, A2000).zip

Why do you want to use this Kickstart? You can boot from hard disk with standard Kickstart 1.3.

**Comment by mras0** [comment] 2022-03-23 18:16
Correct me if I'm wrong, but I think this issue is actually about loadable filesystems (read from RDB).

vAmiga autoboots just fine with that KS version provided the HDF uses OFS.

SCSI.device is not involved in current vAmiga HD support, patching it won't change anything. If you want to autoboot FFS drives with the current version under KS1.3 (and are OK with ROM patching) it's FileSystem.resource you need to patch.

**Comment by rossimariolee** [comment] 2022-03-24 06:01
I have downloaded the latest version of vAmiga (beta).
I have created a HardDisk OFS from menu, then using kickstart 1.3 and workbench 1.3 I formatted using from CLI:
Format Drive dh0: Name HDD QUICK  :  but sometimes it results in a validation error.

Furthermore, if I export the file to be able to restart with the workbench installed on the HDD it happens that vAmiga does not read the exported hdd file: it is greyed out.
So the export of the virtual HDD file does not work and in any case even though copying libraries and directories from the workbench the HDD does not start in autoboot mode, there will be the way to set hdd as default boot media.
So there is not a clear way to set the HDD to boot everytime that emulator starts, as like as an HDD used for a PC Emulator.

Furthermore 128 MB HDD are to low to use WHDLoad software (it could works well with a 68010 and 14mhz clock).

**Comment by mras0** [comment] 2022-03-24 06:47
@rossimariolee Unfortunately OFS doesn't support "large" harddisks (it will appear to work at first, but you get validation errors and the disk is corrupted). I don't know the actual limit is but have seen 50 MB quoted. 40 MB should be fine though. I think the limit is per partition, but haven't checked.

AFAIK whdload requires KS2+, so for that case you can use FFS, which supports larger disks (up to 2GB should work without issues).

Can't really comment on the other issues, but maybe they're resolved by either using KS1.3 + OFS + 40MB disk or KS2 + FFS + for larger disks?

**Comment by rossimariolee** [comment] 2022-03-24 06:53
KS1.3 + OFS + 40MB disk
 FFS + for larger disks

@mras0 thank you for the informations!

So it now I need only **how to set HDD as default at boot** and **how to export it correctly** (if I export I cant load the file it is greyed out)

**Comment by Alvarez81** [comment] 2022-03-24 14:06
An option to make the HD image as default to boot every time VAmiga starts it would be fine for me too.

Whdload games can be loaded from HD and with kick > 3.0 there are no problems to install whdload prog with 68000 (68010 better for quit option).

**Comment by PakkunKinoppi** [comment] 2022-03-25 12:29
Hi, WHDLoad games certainly work better than simple ADFs, no strange configurations or many settings, all is prebuilt in slave.
These games are already sorted, arranged and with a lot of attached documentation.
Having an HD on file, with your favorite games already loaded with WHDLoad creates a functional, fast, and hassle-free system.
Just a workbench with kickstart> 2.05 even just MC68000 (better 68010). But this HD must be bootable automatically when the vAmiga also starts: it must be selectable as default.
Why should all these ADf be loaded for an emulator when in a virtual HD you can put OS and hundreds of games and programs ...?

**Comment by dirkwhoffmann** [comment] 2022-03-26 08:22
Can somebody provide me an HDF with Whdload and some games preinstalled? I'd like to look into it in more detail, but I don't want to walk through the entire installation process. I've never used it before. 

As always: Please don't post any copyright protected stuff on GitHub.

**Comment by dirkwhoffmann** [comment] 2022-03-26 10:02
Just loaded my first game via WHDLoad. Many thanks 😎.

<img width="1016" alt="Bildschirmfoto 2022-03-26 um 10 45 51" src="https://user-images.githubusercontent.com/12561945/160234267-3b6cf0f1-3495-4861-8be1-9e1c477083db.png">

Adding capabilities for persistent HDs could be a nice v2.1 feature. I don't want to add it in v2.0, because it requires some architectural changes. 

As always there are other things to consider, too. If larger hard drives are supported, we run into issues with snapshots, especially when snapshot auto-saving comes into play. I cannot create a new snapshot file every 10 seconds and write a 1GB hard drive into it.

**Comment by Alessandro1970** [comment] 2022-03-26 11:50
Just remove the auto-save for hd files as like as snapshot every some times.
Only save changes on exit for hard drives, or/and a button to save changes. This is my opinion.

**Comment by PakkunKinoppi** [comment] 2022-03-28 06:20
Maybe this issue can be converted from "discussion" to "enhancement" for release 2.1

vAmiga powered with a persistent HD and autoboot at start without select manually the HD would be great...

**Comment by Alessandro1970** [comment] 2022-03-28 06:24
...the same to turn on an A2000 with a Hard Drive fully charged with WHD-games ready to be played !

**Comment by dirkwhoffmann** [comment] 2022-04-01 16:36
I think I've found a user-friendly way to make hard disks persistent (if the user wants to). In the next version, a hard drive can be marked as "sticky" via a new menu item:

<img width="196" alt="Bildschirmfoto 2022-04-01 um 18 16 53" src="https://user-images.githubusercontent.com/12561945/161303029-077c55a4-cc8f-476b-9fb5-dec02d50a720.png">

If a drive is marked that way, vAmiga exports the drive to an HDF inside the user applications folder (which means the user will never see these files under normal circumstances). E.g., when marking HD1 and HD3 as sticky, the following files are created:

```
ls /Users/hoff/Library/Containers/dirkwhoffmann.vAmiga/Data/Library/Application\ Support/vAmiga/Media 
hd1.hdf	hd3.hdf
```

Unmarking a drive as sticky will delete the HDF from that folder. vAmiga interacts as follows with the created files:

- Use case: The user installs the HDR controller board for HD*n*

  vAmiga searches for file hd*n*.hdf in the user applications folder and restores the drive if it is found. If not, a small empty default drive is attached.

- Use case: The user removes the HDR controller board for HD*n*

  If the drive is marked as sticky, the drive is saved to file hd*n*.hdf in the user applications folder.

- Use case: The user closes the application

  All drives that are marked as sticky are saved.

**Comment by dirkwhoffmann** [comment] 2022-04-03 08:01
> it happens that vAmiga does not read the exported hdd file: it is greyed out.

@rossimariolee I haven't been able to reproduce this. Does the name of your exported file end with `.hdf`?

**Comment by rossimariolee** [comment] 2022-04-04 08:26
@dirkwhoffmann ...in those days. Now it seems to work for me.

**Comment by dirkwhoffmann** [comment] 2022-04-08 14:01
The "sticky" feature has been replaced by a true write-through mode in v2.0b2. In write-through mode, an HDF file is created in the applications default folder and updated on-the-fly when a sector is written. When vAmiga launches, it checks the application defaults folder and reuses the HDF if it was found.  Bottom line: To make hard drives persistent, enable write-through mode in the HDx menu and make sure that a hard drive controller is plugged in on startup (go to the Peripherals config panel, enable one or more hard drive controllers and click "Use as default").

**Closed by dirkwhoffmann** 2022-04-08 14:01 UTC
Labels: Enhancement
