### ISSUE TITLE
Audio imperfect on Robocod (James Pond 2)

### ISSUE THREAD

**Issue by Gianmarco72** [dirkwhoffmann/vAmiga#313] opened 2020-04-26 10:29 UTC
The "bass track" disappears during the music both in the title screen and during the game.

Plays fine in SAE.

**Comment by dirkwhoffmann** [comment] 2020-04-26 10:33
Very cool, thanks for reporting! Might be related to the remaining issues in Ghosts'n Goblins. I'll look into it.

**Comment by dirkwhoffmann** [comment] 2020-04-26 15:29
I can replicate it, and I already have a suspect.

I think it's the innocent looking `intreq2` signal which serves as an interrupt request signal inside the audio logic. I think this signal needs to be cleared even if the interrupt request is not served. 

<img width="350" alt="Bildschirmfoto 2020-04-26 um 17 22 49" src="https://user-images.githubusercontent.com/12561945/80312001-25d0fa80-87e3-11ea-8ef5-138a5516b035.png">

The game is very cool, btw. 

<img width="979" alt="Bildschirmfoto 2020-04-26 um 14 55 29" src="https://user-images.githubusercontent.com/12561945/80312006-308b8f80-87e3-11ea-99f9-6f0ed14ecf0a.png">

**Comment by mithrendal** [comment] 2020-04-26 16:22
The colors look very modern ... reminds me on Miami Vice Colors.... oops I feel that I am repeating me ...

**Comment by dirkwhoffmann** [comment] 2020-04-26 16:59
Seems to be fixed in 0.9.2.1. Title music on this screen sounds much better now.

<img width="979" alt="Bildschirmfoto 2020-04-26 um 18 22 46" src="https://user-images.githubusercontent.com/12561945/80314093-89612500-87ef-11ea-8da9-428b87c0609c.png">

Also, I think I deserve that car because I made Crunch Factory work in vAmiga today 😂.

![DhMK7h8WAAAnoqy](https://user-images.githubusercontent.com/12561945/80314106-adbd0180-87ef-11ea-8b82-d7cdce2441a1.jpg)

**Comment by Gianmarco72** [comment] 2020-04-26 17:46
Yep, much better!
But still some problems with "Mrs.Paula" 🙄
Try Road Wars (Melbourne House / Arcadia Systems): no more SFX.
Also the music, that starts immediately on the title screen with high scores, "sounds strange"... still on the bass track 😅

![Road Wars](https://user-images.githubusercontent.com/45571833/80314898-ac420800-87f4-11ea-93a4-d8d341677b4f.jpg)
Works well in v0.9.2

However you absolutely still deserve the "Pac-Car" 😜
Maybe I would prefer a Sinclair C5 Electric Car 😃

![iu-1](https://user-images.githubusercontent.com/45571833/80315128-ef50ab00-87f5-11ea-8ec7-ff1df094c267.jpeg)


@mithrendal Thank you, Mario is a part of my youth 😄

**Comment by dirkwhoffmann** [comment] 2020-04-27 06:25
Just looked at the following two versions of Road Wars:

Road Wars (1988)(Arcadia Systems).adf
Road Wars (1988)(Arcadia Systems)[a2].adf

The first versions has clear issues. It has strange sound and the first splash screen looks like this:

<img width="979" alt="Bildschirmfoto 2020-04-27 um 07 49 01" src="https://user-images.githubusercontent.com/12561945/80339289-95380000-885e-11ea-94a4-3d12c2659f1a.png">

Same thing in UAE. I think this version is broken altogether 🥴. I listened to the sound a few times in vAmiga and UAE, but it sounded pretty similar to my ears. In general, the audio output of both emulators is not 100% identical, because UAE accurately emulates the Amiga's audio filter whereas vAmiga utilizes a simple Butterworth filter from the shelf. The implementation of the resampling algorithms differ, too.

The second version (indexed with [a2]) seems to load fine in both emulators. Music is much better and there is no broken splash screen.

<img width="974" alt="Bildschirmfoto 2020-04-27 um 08 23 14" src="https://user-images.githubusercontent.com/12561945/80340230-8eaa8800-8860-11ea-9ff5-4ee699e5667f.png">

Oh, man, this game is difficult. I didn't manage to survive more than 10 seconds. Maybe we really need that slow motion feature 🤔.

**Comment by dirkwhoffmann** [comment] 2020-04-27 11:30
>  no more SFX.

OK, confirmed. Just experienced this with a different game. I'll look into it...

**Comment by dirkwhoffmann** [comment] 2020-04-27 13:25
I got fooled by the HRM. The old (working) vAmiga code issued a volcntrld command when moving from state 101 to 010 or from state 011 to 010 (volcntrld transfers data from the volume latch to the actual volume register): 

<img width="644" alt="Bildschirmfoto 2020-04-27 um 14 31 34" src="https://user-images.githubusercontent.com/12561945/80376563-4a3bde00-889a-11ea-8d0e-8f2ba6b92ddb.png">

As you can see, the HRM only shows a volctrld command on the 101 -> 010 transition, so I removed the one from 011 -> 010. However, this breaks audio in many games. 

I told Mrs. Paula to update the volume register again on every 011 -> 010 transition and she promised to do so. In return, she requested that audio panel I was talking about in another thread. 

She is very proud to show it to you: 

<img width="640" alt="Bildschirmfoto 2020-04-27 um 14 27 27" src="https://user-images.githubusercontent.com/12561945/80376820-aacb1b00-889a-11ea-9fdc-b8c7a7903639.png">

The panel allows the user to freely mix all four Amiga audio channels. Each channel can be changed individually in volume and distributed freely among the two loudspeakers.

**Comment by Gianmarco72** [comment] 2020-04-27 17:06
Thank you for the technical details, roughly I understood what the problem was (maybe 😅).
However, it's interesting to try to understand how the Amiga's hardware architecture works.

In the meantime I tried the new v0.9.3 and audio seems to be ok, both with Road Wars (my version) and James Pond.
Mrs. Paula seems to be no longer spiteful (we hope so at least 😉).

The panel audio is very cool!

**Closed** 2020-04-29 07:57 UTC
Labels: bug
