### ISSUE TITLE
Strange behavior with video effects + 2.1b4 feedback

### ISSUE THREAD

**Issue by nicolasbauw** [dirkwhoffmann/vAmiga#719] opened 2022-07-18 16:21 UTC
Today, I wanted to try the latest beta on the macbook pro I use for work. It's an Intel machine, I use it with the exact same monitor than my M1 mac. Note : I don't know if it's a 2.1b4 issue (I don't think so), I've never tried vAmiga on this machine before.

I noticed that the video effects menu behaves completely different than on my M1 machine:
- for instance, when I change the dotmask, change is not taken into account unless I reset it to "none". But sometimes, it's taken immediately into account.
- the masks looks completely different than on my M1 machine, especially the bisected mask. It looks nice and subtle on my M1 machine, and on the Intel one it looks ugly and has a moiré pattern:

<img width="889" alt="image" src="https://user-images.githubusercontent.com/37193744/179550061-eef532b4-0402-4f8b-b6d1-48e101907e9c.png">

That seems very strange. I don't even think that's an emulator issue. It's not an important issue for me : I mainly use my M1 machine for vAmiga. I just wanted to report what I noticed.

I can add that on my M1, so far the 2.1b4 works very well, for instance, I do no longer encounter a minor graphics glitch in the dune game. I nearly have the exact same sensations than on a real Amiga, which is the most important aspect for me. One last big thing missing is the vsync : the animations are really not smooth. It's close to perfect.

**Comment by dirkwhoffmann** [comment] 2022-07-20 06:21
@nicolasbauw Thanks for your positive feedback!

I've just run vAmiga on both my Intel and my M1 machine with dotmasks enabled, but I didn't notice any difference. The dotmask effect is applied in the fragment shader to avoid Moiré patterns (with the drawback that the dot size varies between machines). The appearance of a Moiré pattern indicates that your Intel machines applies some rescaling at the very end of the graphics pipeline. Could you check that both of your machines are configured to use the native screen resolution in the Mac display settings?

> when I change the dotmask, change is not taken into account 

I failed to reproduce this issue on both of my machines. I also did a small code review, but didn't find anything (of course there is always the chance that I've overseen something). In theory, changing the dot mask should take effect immediately. The change might be invisible due to rescaling (which seems to happen on your Intel machine) and there is only a subtle difference between the two bisected masks and the two trisected masks (I had problems on my machines to spot the difference without magnifying). However, changing from a bisected to a trisected mask or vice versa should make a visible difference that can be seen with the pure eye.

**Comment by nicolasbauw** [comment] 2022-07-20 08:33
> Could you check that both of your machines are configured to use the native screen resolution in the Mac display settings?

![image](https://user-images.githubusercontent.com/37193744/179930745-77f119ae-2ecb-414b-b063-ab8ddad24b07.png)

That's it. Both machines use a scaled resolution, but a different one, hence a different render. Sorry for that, I didn't even think about it.

> In theory, changing the dot mask should take effect immediately.

Indeed, this morning it does, both on default or scaled display. I don't know why it behaved differently the other day. What still happens is : at launch, even if the mask is set by default on "bisected", it behaves like it's set on "none". I have to go to the menu, change from bisected and any other option, and then go back to bisected for the display to effectively use the bisected mask.

In fact, it looks like it's this only machine that behaves strangely with this menu item in vAmiga. If you don't notice anything particular, you can close the issue.

**Comment by dirkwhoffmann** [comment] 2022-07-27 10:58
Fixed in v2.1b5

**Closed by dirkwhoffmann** 2022-07-27 10:58 UTC
Labels: Bug, v2.1
