### ISSUE TITLE
preferences port 2, joystick usb device set as default not saving

### ISSUE THREAD

**Issue by bnice** [dirkwhoffmann/vAmiga#436] opened 2020-11-05 04:21 UTC
Hi,

When port 2, joystick usb device set in the preferences, then made default, does not get saved. Ideally this would be saved and if the joystick wasn't present when started, it would default back to "no device".

Ben.

**Comment by dirkwhoffmann** [comment] 2020-11-08 18:05
Will be fixed in the next release.

**Comment by bnice** [comment] 2020-11-25 10:55
This bug seems to have survived in 0.9.15?

**Comment by dirkwhoffmann** [comment] 2020-11-25 14:17
It is supposed to work as follows: When "Use as default" is clicked, the port settings are saved (like all other options). Wen the emulator is restarted, the port settings are restored. The only difference to your suggestion is that it doesn't snap back to "None" if the USB device has been removed in the meantime. This is because USB devices are recognized asynchronously which means that there is no specific point in time when we could decide if the port setting should be reset to "None". In this case, it looks like this:

<img width="219" alt="Bildschirmfoto 2020-11-25 um 15 08 29" src="https://user-images.githubusercontent.com/12561945/100238456-828ac400-2f30-11eb-92f9-e0810ae7ea74.png">

As long as no USB device is connected, nothing will be fed into the control port of the Amiga. If the external device is reconnected, it should work as expected. Please let me know if it doesn't work like this on your machine.

**Comment by bnice** [comment] 2020-11-27 10:57
Hi,
I resaved the defaults and got a lot better behaviour. However when I start it without USB joystick device:

<img width="245" alt="Screen Shot 2020-11-27 at 11 41 51 PM" src="https://user-images.githubusercontent.com/1855746/100441670-bc63f200-310b-11eb-8304-476dfd371671.png">

This is how I have my defaults set:

<img width="289" alt="Screen Shot 2020-11-26 at 4 14 12 PM" src="https://user-images.githubusercontent.com/1855746/100442021-40b67500-310c-11eb-8dfb-de608164e343.png">

**Comment by bnice** [comment] 2020-11-30 10:34
Hi,

I am not so worried about what the emulator does when you start without a usb joystick when you have usb joystick set as default and start the emulator without the usb joystick plugged in.  What the correct behaviour is in this case. is debatable (I would go whatever is easiest to code). What is annoying is when you start the emulator without the usb joystick connected and default set to usb joystick and then quit the emulator. Plug in the usb joystick again, check joystick is detected in system report then and restart the emulator and it never sees the usb joystick, quit the emulator again and restart it, then it does see the usb joystick.

**Comment by bnice** [comment] 2020-11-30 10:42
Oh one last thing, the OS X itself seems a bit buggy with when you re-plug in a usb joystick that has previously been plugged in, sometimes it doesn't see it. That is why I check system report to check the usb joystick is detected and/or if its unplugged this is detected correctly. So, if you can't see the problem it maybe OS related. Lastly, I am running Big Sur (MacOS 11).

**Comment by dirkwhoffmann** [comment] 2020-12-06 12:28
I am unsure what the problem is. In your error scenario, do the symbols in the toolbar and the config window differ? The symbols marked with red have to match all the time, as well as the symbols marked with blue.

<img width="641" alt="Bildschirmfoto 2020-12-06 um 13 24 11" src="https://user-images.githubusercontent.com/12561945/101280016-db771980-37c6-11eb-9369-ef21c5b37cfb.png">

If these symbols differ, it's a bug. If not, it's most likely intended behavior.

**Comment by DannyCork** [comment] 2020-12-08 01:11
The symbols are the same for me
![Screenshot 2020-12-08 at 01 10 43](https://user-images.githubusercontent.com/3512672/101424067-4bce8980-38f2-11eb-9515-1572fb5a8513.png)
![Screenshot 2020-12-08 at 01 10 26](https://user-images.githubusercontent.com/3512672/101424071-4d984d00-38f2-11eb-820f-c86b0ce82bf3.png)

**Comment by dirkwhoffmann** [comment] 2020-12-12 07:06
Can I close this?

**Comment by bnice** [comment] 2020-12-13 04:17
Hi,

Sorry about the delay in replying, below are the steps to see issues:

1) Set default Game 1 to mouse
2) Set default Game 2 USB device gamepad
3) Close vAmiga
4) Unplug gamepad
5) Start vAmiga
* vAmiga now changes Game 2 to USB device mouse
6) Plugin gamepad
* vAmiga doesn't detect plugin gamepad, so stays on USB device mouse 

You probably have more important issues to address, so I am ok with you closing this. In English we say "Bigger fish to fry" :-)

**Closed** 2020-12-27 11:55 UTC
Labels: Bug
