### ISSUE TITLE
The process should be halted waiting for the GDBServer to start

### ISSUE THREAD

**Issue by prb28** [dirkwhoffmann/vAmiga#666] opened 2022-03-20 15:19 UTC
I use this script:
```
# Make sure the Amiga is switched off
amiga power off

# Load a Kickstart Rom
memory load rom "./kick13.rom"

# Configure memory
memory set chip 512
memory set slow 512
memory set fast 0

# Set the search path for all connected drives
dfn set searchpath "."

# Insert some ADF
df0 insert "disk.adf"

# Activate the GDB server
server gdb set port 8080
server gdb set verbose true
server gdb attach sys:gencop

# Switch the Amiga on and continue emulation
amiga power on
amiga run
```
As I understand, when the startup-sequence creates the sys:gencop process, there is a check to get the segments here: 
https://github.com/dirkwhoffmann/vAmiga/blob/a87a13b9d4000d06baf4ca24b06350fc512d50f6/Emulator/Misc/OSDebugger/OSDebuggerRead.cpp#L483
this check does not result and the process continues until a second interrupt/server checking.
At this point the segments are retrieved and the gdb server starts.
It seems to me that the process has already executed some instructions before the debugger is attached to it. So we cannot hit a breakpoint at the beginning of the program.
I may be doing something wrong,.
[disk.zip](https://github.com/dirkwhoffmann/vAmiga/files/8311525/disk.zip)
.

**Comment by dirkwhoffmann** [comment] 2022-03-20 15:33
This is due to the current architecture. I know it's not optimal, but I don't know how to do better at the moment. Let me explain some background. vAmiga utilises a launch daemon which is called every 0.5 seconds:

```
void
RemoteManager::serviceServerEvent()
{
    assert(agnus.id[SLOT_SRV] == SRV_LAUNCH_DAEMON);
        
    // Run the launch daemon
    if (serServer.config.autoRun) {
        serServer.shouldRun() ? serServer._start() : serServer._stop();
    }
    if (rshServer.config.autoRun) {
        rshServer.shouldRun() ? rshServer._start() : rshServer._stop();
    }
    if (gdbServer.config.autoRun) {
        gdbServer.shouldRun() ? gdbServer._start() : gdbServer._stop();
    }

    // Schedule next event
    agnus.scheduleInc <SLOT_SRV> (SEC(0.5), SRV_LAUNCH_DAEMON);
}
```

In this routine, it checks if one of the three remote servers should be launched. In case of the gdb server, `shouldRun` looks like this: 

```
bool
GdbServer::shouldRun()
{
    // Don't run if no process is specified
    if (processName == "") return false;
    
    // Try to locate the segment list if it hasn't been located yet
    if (segList.empty()) readSegList();

    return !segList.empty();
}
```
 
In other words: vAmiga uses polling to check if a process has been created and because polling for a process is expensive, it is done only twice a second. The optional solution would be to intercept at the exact point where the process is created, but I have no idea how this could be done.

**Comment by prb28** [comment] 2022-03-20 16:10
Thanks for the insight, I though that the processes were managed by the emulation. But from what I understand of your explanation, it in the kernel so you must check from outside.
I know that fs-uae/winuae has some 68k assembly code with callbacks (traps) for some functions. The emoon implementation of gdb protocol in uae used that to start the program without a startup-sequence.

**Comment by dirkwhoffmann** [comment] 2022-03-20 17:08
Would it be possible and acceptable to induce a `move` command at the beginning of the generated executable? If so, the program could interrupt the emulator itself by writing a magic value at some magic address in unmapped memory.

**Comment by mras0** [comment] 2022-03-20 18:54
Just a quick brainstorm.

How about something like:
    - Debugger saves first program instruction word and replaces it with e.g. `TRAP #8` (before writing it to ADF/HDF)
    - Starts vAmiga with feature 1 active
    - Stopped, put (read) breapoint at TRAP 8 vector, restarts execution
    - Trap8 vector hit, performs sanity check, restores first instruction word and makes exception go away

Feature 1: Needs a retrorshell and/or (proprietary) gdb remote command that's similar to UAE "f" debugger command (Step forward until PC in RAM ("boot block finder")). I.e. pause first time PC is in RAM.
With this we know that KS has finished (caveat: DOS isn't initialized though). Could also be useful for debugging track loaded demos/games that forego the OS. I think this should also work with AROS.

Feature 2-X: Seems like there are some other GDB commands that need to be implemented for this to work.

Pros:
    - Should work with any KS version, no differences to "real" usage
    - Could support debugging trackloaders/bootblocks
    - Few changes in vAmiga, and none of which could break anything (hopefully)

Cons:
    - More complicated debugger code, maybe not compatible?
    -  Slower than loading EXE directly

**Comment by dirkwhoffmann** [comment] 2022-03-20 21:23
That's inspiring. But can't we make it even simpler? Here is what came to my mind:

- Debugger replaces first instruction with `TRAP #8`.
- Debugger activates special trap mode in vAmiga and passes in the original opcode.
- When `TRAP #8` is executed, vAmiga writes no stack frame. Instead, it 
  - pauses emulation,
  - replaces `TRAP #8` by the original opcode,
  - redirects the PC to the original instruction.

Right now, RetroShell has no breakpoint commands which should be changed anyway. Besides standard commands for setting and removing normal breakpoints, it could offer commands for managing a new kind of breakpoints ("trappoints"?)

Variant 1: `cpu trappoint 8`
Semantics: Emulation pauses whenever `TRAP #8` is executed. This would be a handy way to pause the emulator from within the Amiga.

Variant 2: `cpu trapppoint 8 <opcode>`
Semantics: As explained above. Emulation is paused and TRAP replaced by `<opcode>`.

**Comment by prb28** [comment] 2022-03-20 21:45
I think you should keep in mind that it should be used by a standard gdb. So if there is a replacement to do it must be done in vAmiga.
Although it can be a command in script to prepare an executable for debugging.

**Comment by dirkwhoffmann** [comment] 2022-03-20 21:56
> So if there is a replacement to do it must be done in vAmiga.

This is difficult, because as long as we want to pass the program to vAmiga via an ADF, the emulator has no chance of knowing what to patch.

Isn't the following workflow possible? 

- The VSC plugin compiles the source file
- The VCS plugin replaces the first instruction word (e.g., 123456) by `TRAP #8` 
- vAmiga is called with a script containing the statement `cpu trappoint 8 123456` 
- Write everything to an ADF and launch vAmiga 

vAmiga would run as usual until the `TRAP #8` instruction is encountered. It would pause and send a command to the GDB debugger that a breakpoint has been reached.

**Comment by prb28** [comment] 2022-03-20 22:09
Yes adding or modifying something in the binary is possible with the plugin but you'll not be able to do it with a standard gdb so if you want to use bebbo / bartman plugins or a raw gdb it will be difficult.
What about having a script command after the adf loading that modifies the binary?
Like:

df0 insert "disk.adf"
Debug wrap df0:/mybinary

**Comment by dirkwhoffmann** [comment] 2022-03-21 07:36
> Debug wrap df0:/mybinary

Yes, this is doable. But a lot of overhead would be involved. vAmiga would have to convert the ADF to a file system, search for the file, apply the modification, and convert the file system back to an ADF. 

What I don't like that much about the approach is that we had to hide this command from the user. That is because
- it's not possible to describe in simple words what `debug wrap` is doing,
- having two `debug wrap` statements in a row would screw up the internal logic.

Hence, it would be some of those internal magic commands that are frequently used in real-life software, but usually indicate bad software design.

**Comment by mras0** [comment] 2022-03-21 17:42
Taking a step back, the main issue with the existing solution is that the emulator doesn't have a good (cheap) way of knowing when a new process (in particular the one of interest) has started, right?

I'm thinking maybe adding a "debug controller" board (only when needed, obviously) like the HD controller could be an option.  It could hook e.g. exec/AddTask (or maybe some other function(s) is better) and signal to the emulator that it should re-check the OS structures. Later on this could also serve as the extension point for possibly implementing something like the "run executable directly" functionality that seems to be present in the *UAE versions.

I've only had a cursory look at how it's implemented in the UAEs, but I think it relies on extending the boot rom (where e.g. harddisk functionality etc. already lives).

The retroshell extensions proposed in the linked issue would complement this and not replace it.

P.S. the reason for suggesting `TRAP #8` was just that it's a single instruction word and probably not otherwise commonly used in Amiga software, any exception would obviously do, but e.g. illegal instructions occur as part of normal KS startup on a plain 68000.

**Comment by dirkwhoffmann** [comment] 2022-03-21 21:57
Debug controller board 😎. I already like it. Great idea!

**Comment by mras0** [comment] 2022-03-23 17:50
Of course it's not as easy as I imagined. A new task (or process) isn't created for each command run from the CLI, and even if such a debug board could hook DOS functions (which it can't easily do, since DOS isn't loaded when it's initialized) there isn't a single externally visible point to hook...

However, I think I've devised a hacky way to still accomplish the task (no pun intended), but it's still very much work in progress.

Here's a very small (and still experimental, only tested with KS1.3) debug expansion rom (similar to the HD controller one): [debug_exprom.zip](https://github.com/dirkwhoffmann/vAmiga/files/8335225/debug_exprom.zip)

It only does one thing: On startup it hooks exec.library/AddTask and notifies the emulator by writing the Task pointer to board base + 0x40. This should probably trigger a recheck to see if the wanted process is available, but it probably isn't in most (all?) cases.

Now the hacky part: If the task has node type NT_PROCESS (`task_ptr + 8 /*ln_Type*/ == 13`) set a memory write breakpoint at `task_ptr + 0xb0 /*pr_ReturnAddr*/` and trigger a rescan when it's hit. If the process is found, it's just about to start, but the segment list can be scanned to set a proper break point at the first instruction word (it's always the first word of the first segment). For the very simple use-case you could restrict this to processes where `task_ptr + 10 /*ln_Name*/ == "Initial CLI"`

**Comment by dirkwhoffmann** [comment] 2022-03-23 20:01
> Now the hacky part

I can try this, but it feels more complicated than the `TRAP` approach. The watchpoint handler would have to communicate with the GDB server which seems a little weird. Moreover, vAmiga doesn't distinguish between memory reads and memory writes in the context of watchpoints. Maybe it's simpler to try the `TRAP` approach first. 

Instead of a `TRAP` instruction, it would also be possible to induce a LINE-A or LINE-F instruction. There are plenty of them, so it would even be possible to transmit a 12-bit payload (which isn't needed though).

**Comment by mras0** [comment] 2022-03-24 06:57
> I can try this, but it feels more complicated than the `TRAP` approach. The watchpoint handler would have to communicate with the GDB server which seems a little weird. Moreover, vAmiga doesn't distinguish between memory reads and memory writes in the context of watchpoints. Maybe it's simpler to try the `TRAP` approach first.

It was meant as an alternative to polling in the gdb server waiting to start without having to modify the executable. It's been a while since I looked at it, but doesn't the gdbserver already have a way to be notified about watchpoints being hit? For this purpose either a read or write watchpoint would work.

But of course, try whatever approach you think is best.

> Instead of a `TRAP` instruction, it would also be possible to induce a LINE-A or LINE-F instruction. There are plenty of them, so it would even be possible to transmit a 12-bit payload (which isn't needed though).

You may want to avoid $Fxxx instructions as they are legitimately used for floating point operations. $Axxx is fine though, and that is how *UAE implements its traps (with a payload like you're envisioning). It only interprets them as traps if they're found in the extension ROM though.

**Comment by mras0** [comment] 2022-03-26 19:02
FWIW it (the debug board method) works in practice (including AROS):
![image](https://user-images.githubusercontent.com/9952017/160252790-a541d61d-0d65-49c7-a6dc-de96a234c4f3.png)

Since having this many CPU watchpoints isn't free it's probably something that should be disabled with compile time flags by default, but being able to break when a new (or specific) process starts seems useful enough that I'll be adding it to my own emulator.

**Comment by dirkwhoffmann** [comment] 2022-03-27 05:46
>  FWIW it (the debug board method) works in practice (including AROS):

Great job! My plan is to implement both approaches in vAmiga to get a feeling for their advantages and disadvantages. I see a lot of potential in the debug board approach, because it can be extended with lots of other functionalities by just replacing the Rom. Instruction trapping has it's own advantages. It is conceptually simple and has no negative effect on emulation speed.

Thanks for pointing out the LINE-A and LINE-F differences. I'll go for LINE-A instructions then. At the end, vAmiga will provide four different debugging aids:

- *Breakpoints* for observing the program counter.
- *Watchpoints* for observing the address bus.
- *Catchpoints* for observing exception vector space.
-  *Software traps* for observing LINE-A instructions.

**Comment by dirkwhoffmann** [comment] 2022-03-27 12:12
Brief update: Software traps seem to work. There will be a new RetroShell command

    df<n> catch <filename>

which replaces the first opcode of the specified executable on disk. E.g., in the following example, the Preferences app and the Clock app on the workbench disk are "catched":

<img width="1034" alt="Bildschirmfoto 2022-03-27 um 13 56 49" src="https://user-images.githubusercontent.com/12561945/160280501-406c8bf0-3744-4fba-9efa-d08d80df2e4d.png">

When double-clicking the Preferences icon, emulation stops:

<img width="980" alt="Bildschirmfoto 2022-03-27 um 13 56 00" src="https://user-images.githubusercontent.com/12561945/160280524-7d0c5517-57fc-423e-bf49-037d5305e5b5.png">

The solution works as expected, but is pretty complicated from a technical point of view. The following  code snippet provides some insight into what is going on internally: 

```
void
FloppyDrive::catchFile(const string &path)
{
    {   SUSPENDED
        
        // Extract the file system
        auto fs = MutableFileSystem(*this);
        
        // Seek file
        auto file = fs.seekFile(path);
        if (file == nullptr) throw VAError(ERROR_FILE_NOT_FOUND);
        
        // Extract file
        Buffer<u8> buffer;
        file->writeData(buffer);
        
        // Parse hunks
        auto descr = ProgramUnitDescriptor(buffer);
        
        // Seek the code section and read the first instruction word
        auto offset = descr.seek(HUNK_CODE);
        if (!offset) throw VAError(ERROR_HUNK_CORRUPTED);
        u16 instr = HI_LO(buffer[*offset + 8], buffer[*offset + 9]);
        
        // Replace the first instruction word by a software trap
        auto trap = cpu.debugger.swTraps.create(instr);
        buffer[*offset + 8] = HI_BYTE(trap);
        buffer[*offset + 9] = LO_BYTE(trap);
        
        // Write the modification back to the file system
        file->overwriteData(buffer);
        
        // Convert the modified file system back to a disk
        auto adf = ADFFile(fs);
        
        // Replace the old disk
        swapDisk(std::make_unique<FloppyDisk>(adf));
    }
}

```

**Comment by mras0** [comment] 2022-03-27 16:08
Cool! Though it looks like you should probably replace the existing instructions before showing the debugger window (but I guess you're already working on that).

Regarding the "debug board", I've found a much better method, but unfortunately it doesn't work with KS1.3, though hopefully that's just temporary (fingers crossed).

Of course it's also a major hack, but it's much nicer than the previous one:
 - Expansion rom hooks exec.library/AddLibrary and waits for dos.library to be added
 - It then hooks [dos.library/LoadSeg](http://amigadev.elowar.com/read/ADCD_2.1/Includes_and_Autodocs_2._guide/node02C5.html) (and removes the hook for AddLibrary)
 - First it calls the real LoadSeg method and on success it notifies the emulator about the name (executable) and segment list
 - The emulator can then (if the executable is the right one) either add a breakpoint at the first instruction or patch it at its convenience

For KS2.0+ and AROS it works as expected, but it seems like KS1.3 either hasn't initialized the library vectors yet (best case) or anther method is necessary there.

**Comment by dirkwhoffmann** [comment] 2022-03-27 16:21
> Though it looks like you should probably replace the existing instructions before showing the debugger window

Yes, I though so, too. I have to add some `peek` wrapper to the disassembler that replaces "catched" instructions on-the-fly.

 > Regarding the "debug board", I've found a much better method

Cool. I've already added the board to vAmiga as a stub (named DiagBoard at the moment). It is enabled if debug option DIAG_BOARD is set to 1. At the moment, the board does nothing, but identifying itself to Kickstart via the autoconfig procedure.

**Comment by mras0** [comment] 2022-03-27 17:23
While I try to figure out a way to make it work in KS1.x (disassembling BCPL code is so fun), you can try this updated version:
[debug_exprom.zip](https://github.com/dirkwhoffmann/vAmiga/files/8358093/debug_exprom.zip) if you want.

It writes one or two (32-bit) pointers to BOARDBASE+0 an +4 (i.e. 0x40/0x44) and (16-bit) commands to BOARDBASE+0x10. The interesting one (for KS2+) is command 4 where the first pointer (written to 0x40) is a normal C-string containing the executable and the second pointer is a BPTR to the segment list (if the executable matches, you want to put the breakpoint at PTR2*4+4). (Command 1 is AddTask being called with PTR1=task).

**Comment by mras0** [comment] 2022-03-28 17:56
Managed to also get it working under KS1.3. I won't bore with the details, but suffice to say it's extremely (patching FindTask andreplacing BCPL global vector entry...). As header: [debug_exprom.zip](https://github.com/dirkwhoffmann/vAmiga/files/8365044/debug_exprom.zip). It now works with KS1.3, KS2.0+ and AROS. 

However trying to test with KS1.2 I noticed that just having the debug board attached makes it crash very early (before the expansion ROM is even called). This also seems to be the case in vAmiga with the "old" (current in dev branch) rom. Will debug it, but something to be aware of.

**Comment by dirkwhoffmann** [comment] 2022-03-29 12:21
The debug board almost works in vAmiga. With the board plugged in, I can "catch" a task via new RetroShell command `os catch <task name>`: 

<img width="1034" alt="Bildschirmfoto 2022-03-29 um 13 54 36" src="https://user-images.githubusercontent.com/12561945/160608332-74b5faf3-765e-4479-8f2e-4eda6ad24018.png">

After launching the Clock app, emulation does stop 😎: 

<img width="1034" alt="Bildschirmfoto 2022-03-29 um 14 07 39" src="https://user-images.githubusercontent.com/12561945/160608541-16176610-3c70-4ee1-9547-9db5efbe86ee.png">

<img width="980" alt="Bildschirmfoto 2022-03-29 um 14 07 29" src="https://user-images.githubusercontent.com/12561945/160608582-7dfec8e4-e800-4c67-887f-04e8de90b017.png">

However, I've run into a strange problem. In the test above, my debug log reads as follows:

    DiagBoard:257 LoadSeg: 'Clock' (302187)
    DiagBoard:203 Added Process 'Clock'

After repeating the test, I got this ('P' is sometimes 'x' or a different character):

    DiagBoard:257 LoadSeg: 'ClockP' (302187)
    DiagBoard:203 Added Process 'Clock'

There seems to be an issue with the null-termination of the string received in `LoadSeg`.

**Comment by mras0** [comment] 2022-03-29 16:10
Great!

> However, I've run into a strange problem. In the test above, my debug log reads as follows:
>  [snip]
> There seems to be an issue with the null-termination of the string received in `LoadSeg`.

Damn, I was hoping you wouldn't ~~notice~~ encounter this. It's because in 1.3 the filename is a BSTR (i.e. length prefixed and a BPTR), so I just passed `D1*4+1` to the debug board to keep the interface unchanged, and in my limited testing they were all NUL-terminated (in KS2.0 it's common (always done?) for BSTR's to also be NUL-termined for easy interop, so I was hoping it was the same).

Now it looks (again from limited testing) that the name is always stored in RAM, so it could be fixed by the expansion ROM temporarily NUL-terminating the string (and restoring the old value later on), but I don't know if that's another unwarranted assumption, and we should just have either two different operation codes or signalling that it's a BSTR by setting the MSB.

**Comment by dirkwhoffmann** [comment] 2022-03-29 16:35
> It's because in 1.3 the filename is a BSTR 

Ah, OK, I see. That clarifies everything.

> and we should just have either two different operation codes

I think that's the cleanest way. Either pass an additional bool parameter (indicating the string format) or split the LoadSeg callback into two.

Overall, the debug board is great. Originally, I thought the `TRAP` method is superior, but now I think the opposite is true. The debug board is much more flexible and much simpler to use.

**Comment by mras0** [comment] 2022-03-30 15:57
Figured out what the issue is with KS1.2.... IT'S A PIECE OF JUNK. Ahem, more precisely expansion.library/ConfigBoard is broken if the expansion board has a diag routine. This also affects the harddrive controller ROM. It can be fixed by patching the following words (offset from start of KS rom):
```
        0x4d9c: 0x2c6e -> 0x426f
        0x4d9e: 0x0024-> 0x0004
        0x4db2: 0x0002 -> 0x0000
```
With that both debug board and HD work as expected (though of course, autoboot still doesn't work). I must have misremembered about the HD working in 1.2 previously.

Also changed debug board rom, so it now uses operation code 5 if the filename is BSTR.

**Comment by mras0** [comment] 2022-03-30 18:56
> Noooooooo. My original A500 came with Kickstart 1.2 back in the day. Still love it 😉.

Same, and although it's long since died, I still miss ye olde red power LED :) I may be too harsh, as the programmers seem to not have had access to hardware that used this feature.

Details:
```
; D3 contains cd_BoardAddr + er_InitDiagVec (i.e. address of diag routine)
; A4 contains function pointer to copy routine (exec.library/CopyMem for DAC_WORDWIDE)
; A6 contains ExecBase
; A7 points to struct DiagArea (size: $0e)

00fc4d94  302f 0002                 MOVE.W	$0002(A7), D0   ; D0 = da_Size
00fc4d98  7200                      MOVEQ.L	#$00, D1
00fc4d9a  2f0e                      MOVE.L	A6, -(A7)
00fc4d9c  2c6e 0024                 MOVEA.L	$0024(A6), A6   ; BUG1
00fc4da0  4eae ff3a                 JSR 	$-00c6(A6)      ; Supposed to call exec.library/AllocMem
00fc4da4  2c5f                      MOVEA.L	(A7)+, A6
00fc4da6  4a80                      TST.L	D0
00fc4da8  672a                      BEQ.B	$00fc4dd4
00fc4daa  2400                      MOVE.L	D0, D2
00fc4dac  2240                      MOVEA.L	D0, A1
00fc4dae  2043                      MOVEA.L	D3, A0
00fc4db0  202f 0002                 MOVE.L	$0002(A7), D0   ; BUG2
00fc4db4  4e94                      JSR 	(A4)
```
BUG1: Author thinks A6 contains ExpansionBase here (and wants to get ExecBase from eb_Private02), but since A6 already holds ExecBase it's actually LowMemChkSum+upper part of ChkBase (i.e. garbage). This is why it Gurus.

BUG2: This should be a word access (since da_Size is an UWORD), but that's not sufficient as D0 previously held a pointer (upper word should be cleared, either way way it'll try to copy way too much stuff).

Patch changes fc4d9c to be `CLR.W 4(A7)` and fc4db0 to `MOVE.L 0(A7), D0` fixing both issues.

**Comment by dirkwhoffmann** [comment] 2022-03-31 13:20
I've upgraded the debug board and crawled through the Rom database. vAmiga knows about five different Kick 1.2 Roms (the latter two are Guardian patches):

       case 0x9ED783D0: return ROM_KICK12_33_166;
       case 0xA6CE1636: return ROM_KICK12_33_180;
       case 0xDB4C8033: return ROM_KICK121_34_004;
       case 0x85067666: return ROM_KICK12_33_180_G11R;
       case 0x74680D37: return ROM_KICK13_34_005_G12R;

`ROM_KICK12_33_166` was uses in the A1000 and stores `expansion.library/ConfigBoard` at a different location. I therefore implemented the patch code in a flexible way: 

```
   switch (romIdentifier()) {

        case ROM_KICK12_33_166:
        case ROM_KICK12_33_180:
        case ROM_KICK121_34_004:
        case ROM_KICK12_33_180_G11R:
        {
            for (isize i = 0; i < KB(256) - 22; i += 2) {
                
                if (R16BE(rom + i)      == 0x2c6e &&
                    R16BE(rom + i + 2)  == 0x0024 &&
                    R16BE(rom + i + 4)  == 0x4eae &&
                    R16BE(rom + i + 6)  == 0xff3a &&
                    R16BE(rom + i + 20) == 0x202f &&
                    R16BE(rom + i + 22) == 0x0002) {
                    
                    msg("Patching Kickstart 1.2 at %lx\n", i);
            
                    W32BE(rom + i, 0x426f0004);
                    W16BE(rom + i + 22, 0x0000);
                    return;
                }
            }
            warn("Can't find patch location\n");
            break;
        }
```

With my Kick 1.2 version (ROM_KICK12_33_180), patching works fine:

<img width="980" alt="Bildschirmfoto 2022-03-31 um 15 07 43" src="https://user-images.githubusercontent.com/12561945/161062652-a388b15b-8a7f-4209-9abe-58dd96ec2c5c.png">

Patching has the negative side effect of changing the Roms CRC. As a result, it is now longer recognized by the emulator:

<img width="642" alt="Bildschirmfoto 2022-03-31 um 15 07 59" src="https://user-images.githubusercontent.com/12561945/161063068-da04bfb8-84bf-492e-8306-57fc9fe1c5b2.png">

To cope with this, I've added the patched Rom to the database, too. Instead of a contaminated Rom, the user will see this: 

<img width="642" alt="Bildschirmfoto 2022-03-31 um 15 09 17" src="https://user-images.githubusercontent.com/12561945/161063373-c512d794-f9a9-400a-b105-66c96c5724e9.png">

**Comment by dirkwhoffmann** [comment] 2022-03-31 14:07
@prb28: All missing parts should be there by now (I just merged everything from the dev branch into the master branch).

- To pause emulation when a certain process launches, 

  - plug in the debug/diagnose board via RetroShell command `os set diagboard 1` (Amiga must be powered off).
  - specify a task to wait for via RetroShell command `os catch <filename>`

Command `df0 catch <filename>` is deprecated and will go away.

**Comment by dirkwhoffmann** [comment] 2022-04-08 13:56
Part of v2.0b2 which is now online.

**Closed by dirkwhoffmann** 2022-04-08 13:56 UTC
Labels: Discussion
