### ISSUE TITLE
Old Anthrox Intro

### ISSUE THREAD

**Issue by chris70c** [dirkwhoffmann/vAmiga#588] opened 2021-10-27 02:28 UTC
Seems to stutter quite a bit, doesn't work at all in WinUAE (4.4).
[AYN8T7H9R5O4X.zip](https://github.com/dirkwhoffmann/vAmiga/files/7422677/AYN8T7H9R5O4X.zip)

**Comment by dirkwhoffmann** [comment] 2021-11-06 10:54
Issue #597 has to debugged first.

**Comment by dirkwhoffmann** [comment] 2021-11-07 13:58
Findings: In vAmiga, the demo boots sometimes, but not always. There is some indeterminism involved. If the disk is present when the emulator resets, it boots fine. If the disk is inserted manually after the hand&disk logo shows up, it might or might not boot. On my A500, it never boots, no matter when the disk is inserted (aka when the USB stick is plugged into the Gotek drive).

@mithrendal: Could you occasionally run the demo on the A1000? The demo might be too old to be compatible with the "new" machines. 

What we need is a sound recording. In vAmiga, the music sounds like there are some speed issues (in German: "Die Musik leiert ein wenig". I don't know how to correctly express "leiern" in English in this context).

@chris70c: With "Seems to stutter quite a bit", you are relating to audio, aren't you?

**Comment by chris70c** [comment] 2021-11-07 14:06
Not only the audio, the stars background and the 2 lines opening up at the beginning seems to follow the audio stutter (or the other way around).

**Comment by dirkwhoffmann** [comment] 2021-11-07 14:11
> Not only the audio

@mithrendal: We need a full video of that demo 😎

[OldAnthrox.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/7492423/OldAnthrox.adf.zip)

**Comment by dirkwhoffmann** [comment] 2021-11-07 14:23
This is a recording made with vAmiga 1.1b6: 

https://user-images.githubusercontent.com/12561945/140648978-a4b9c313-2c54-4b68-bcd2-150f8c23d15d.mov

**Comment by chris70c** [comment] 2021-11-07 14:32
Yes that is basically how it looks here too, the stars are kinda jumpy the scroll isn't smooth, now it might be that the demo is like that given that it doesn't work in WinUAE I don't have anything to compare it with; the ideal would be to see it runs on a real machine but if it doesn't work on your A500 it probably needs either an early version with KS1.2 or an A1000 with KS 1.1.
Gonna try some more with WinUAE to see if I can make it runs somehow and I'll let you know.

**Comment by chris70c** [comment] 2021-11-07 14:36
Ok, it works in WinUAE with a quickstart A500 config 512K chip only and Kickstart 1.1 (PAL), doesn't work with any KS newer than that; it looks the same as in vAmiga, jumpy scroll and audio stutters so it may just be a really old and bad coded demo, need real hardware verification I guess.

**Comment by mithrendal** [comment] 2021-11-12 05:35
😱 Totally missed this issue. Just read it today 🤭. Ancient A1000 will flooded with a fresh stream of electrical charged particles very soon…

**Comment by mithrendal** [comment] 2021-11-12 20:44
https://user-images.githubusercontent.com/17108995/141531935-5b7300dd-007c-4faa-8a15-2bf87137d83e.mov

A1000 Kickstart 1.1

**Comment by chris70c** [comment] 2021-11-12 20:47
Seems more or less the same as on both emulators, I guess is just a very old and not too good coded intro :)

**Comment by mithrendal** [comment] 2021-11-12 20:48
and it starts only in 1 of 4 attempts or so ... when it does not start then the screen stays stuck like so

**Comment by mras0** [comment] 2021-11-13 18:03
I think the issue with this one is that the author had a too beefy machine (perhaps even the one that's bragged about running the BSS: 40 MHz 68030 w/ 16MB fastram)! It works fine in WinUAE (4.9.0 b39) with specs like that without stuttering etc.

Its main problem is that it doesn't kill the system and set up it's own interrupt routines or really anything like that, but still pretends it owns the system.

The main loop relies on polling INTF_COPER ($0010) in intreqr (set by the copperlist), but it leaves systems interrupts enabled for level3 (copper+vertb), and the normal system level 3 will acknowledge the copper interrupt making the loop hang. So what I think happens most of the time is that it simply gets stuck there, but sometimes it gets lucky and gets into a "good groove" where it can do its stuff and win the race against the system interrupt in reading intreqr most of the time.

Though I haven't looked at it too closely, I think the music stuttering is caused by the code getting stuck in the main loop (losing the race with the system interrupt routine(s)) or maybe just mismanagement of CIA timers (again it seems to use polling instead of setting up interrupt routines).

Below is a partial disassembly of what the initial setup/main function (after it's finished it's unpacking using RNC).

**Bottom line: vAmiga is probably fine here** :)

```
Start                           	; $0001d550 CODE
	MOVEM.L	D0-A6, -(A7)
	MOVEA.L	AbsExecBase, A6
	JSR	_LVOForbid(A6)
	BSR.W	SelectSomeSprite1
	LEA.L	CustomBase, A0
	MOVE.W	DMACONR(A0), OldDMACON
	BSET.B	#7, OldDMACON
	MOVE.W	INTENAR(A0), OldINTENA
	BSET.B	#7, OldINTENA
	MOVE.W	#$7fff, DMACON(A0)
	MOVE.W	#$7fff, INTENA(A0)
	MOVE.L	#copperlist_00020530, COP1LCH(A0)
	MOVE.W	#$83e0, DMACON(A0)
	MOVE.W	#$c010, INTENA(A0)   ; Enable copper interrupt!!
	CLR.W	COPJMP1(A0)
	BSR.W	SetBitplanePointers
	MOVE.L	#$00042c50, D0
	MOVE.W	D0, copperlist_00020530+$9a
	SWAP.W	D0
	MOVE.W	D0, copperlist_00020530+$96
	LEA.L	dat_00020b48, A0
	BSR.W	func_0001d9d2
.MainLoop            	; $0001d5cc CODE
	AND.W	#$0010, intreqr ; Check for copper interrupt
	BEQ.B	.MainLoop
	BSR.W	Main
	BTST.B	#6, ciaapra	; bit 6 = /FIR0
	BNE.B	.MainLoop
```

**Comment by chris70c** [comment] 2021-11-13 19:29
I doubt about those specs, the intro is from 1987 :)

**Comment by mras0** [comment] 2021-11-13 20:10
> I doubt about those specs, the intro is from 1987 :)

Didn't realize it was that early, so yeah, you're probably right that it's unlikely/impossible to have an Amiga with those specs. It's a bit hard to find a chronological list of available expansion boards, but it seems like it would be possible to have a 68020 at that time e.g.: http://amiga.resource.cx/exp/csa1020 and that or better seems to be all that's required to make it work as the author probably intended.

**Comment by chris70c** [comment] 2021-11-13 20:16
Nah, trust me, I had computer shop my entire life in Italy, back in 1987 there was nothing available, at least not at reasonable prices, this is just a bad coded intro and it might even be earlier than 1987 given that it works only with Kickstart 1.1 which was never on anything but A1000; all A500 came out with Kickstart 1.2 or newer and there were no 68020 expansions for the A1000 back in the day.

**Comment by mras0** [comment] 2021-11-13 20:38
> Nah, trust me, I had computer shop my entire life in Italy, back in 1987 there was nothing available, at least not at reasonable prices, this is just a bad coded intro and it might even be earlier than 1987 given that it works only with Kickstart 1.1 which was never on anything but A1000; all A500 came out with Kickstart 1.2 or newer and the 68020 expansions for the A1000 back in the day were almost impossible to find; 68020 + Kickstart 1.1 = doesn't work at all.

Just to be clear, at least with WinUAE it doesn't require KS1.1. It appears to work just fine on all kickstarts 1.2+ (even on 3.1!) as long as you have a 68020+ CPU (e.g. A1200 quickstart). FWIW 68010+Fast RAM doesn't seem to work. Probably related to whether the polling loop is in CPU cache.

Whether that's a plausible explanation for why it's coded like that or if the original coder had access to a 68020+ you're much better judge. The code is buggy and wrong for sure :)

**Comment by chris70c** [comment] 2021-11-13 20:42
That's either a quirk in WinUAE or some weird result of using a 68020 with Kickstarts that weren't really meant to be used on anything but 68000; the most likely explanation is that this is a really old intro (early 87, late 86 is the best guess) and back then information and documentation was really hard to find and extremely expensive so people was just trying to guess how things worked, that is the reason you find a lot of weird code around that works only on specific configurations or specific roms; I got my first A1000 in 85 and there wasn't a single page of hardware documentation, no internet either so we were all playing around with registries and stuff just to see what they were doing :)

**Comment by mras0** [comment] 2021-11-14 16:05
I researched a bit more, only because I got curious, and it's fun to dig into this stuff :)

I found the intro on [pouet](https://www.pouet.net/prod.php?which=41997) - Unforunately doesn't mention when it was released.

[This](http://janeway.exotica.org.uk/release.php?id=8092) entry seems to match: Title is "Accuracys bbs (Intro)", Accuracy is mentioned in the scroll text as being the sysop and the coder is listed as "Cobra (Anthrox)", which also matches the scroll text.

It doesn't have any download or screenshot though, but it does mention that it uses [Prorunner 2.0](https://www.pouet.net/prod.php?which=50015) and with that clue I could see that that is indeed the music player (much easier when you have the source available). Maybe it used [version 1](https://demozoo.org/productions/256834/) from October of 1992, I haven't checked that thoroughly.

I also found the BBS mentioned ("The Wall") and it also mentions Accuracy (named as operator in the text) as running it [here](http://janeway.exotica.org.uk/author.php?id=53871) listing it as active from at least 1995-1998, but it probably operated earlier as well.

According to [this document](http://www.textfiles.com/artscene/history/scenery/scenery/all.txt) "Anthrox was an English illegal group, born as early as 1989 (though they were announced as a new group in Zine #5, released 06/90)"

Like I wrote earlier, the intro is compressed using Rob Northen Compression, which [this](https://segaretro.org/Rob_Northen_compression) site claims was developed in 1991 (matches the copyright in the [aminet](http://aminet.net/util/pack/RNC_ProPack.lha) archive).

All in all, I think this intro was released in late 1992 at the earliest, meaning it isn't unlikely that the author had a 68020.

**Comment by dirkwhoffmann** [comment] 2021-11-14 17:25
That's all very interesting. Maybe we can find out who the author is and let him join our team. 😎

**Comment by chris70c** [comment] 2021-11-14 20:10
@mras0: you're absolutely right, my mistake I don't know why I was thinking about another old intro from the same group.

**Closed** 2021-11-20 04:36 UTC
Labels: Needs verification
