### ISSUE TITLE
Cybernoid II crashes on vAmiga

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#106] opened 2019-07-19 07:46 UTC
HI, while plaiyng the first level of Cybernoid 2 full cheat ...the vAmiga quits itself, here I put the crash message.

Report:
[CRASH.TXT](https://github.com/dirkwhoffmann/vAmiga/files/3409984/CRASH.TXT)

Game:
[Cybernoid II - The Revenge (1989)(Hewson)[cr Subway - Dream Team][t +4 Subway - Dream Team].adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3409985/Cybernoid.II.-.The.Revenge.1989.Hewson.cr.Subway.-.Dream.Team.t.%2B4.Subway.-.Dream.Team.adf.zip)

**Comment by dirkwhoffmann** [comment] 2019-07-19 11:53
😲 A crash in the FastBlitter.

It crashes here: 

       if (useD) {
                mem->poke16(bltdpt, dhold);
                assert(bltdpt);
                INC_OCS_PTR(bltdpt, incr);

The Blitter writes to Chip Ram address 0 which I never expected to happen.
I'll remove the assert statement in the next release. If the write to this address was supposed to be correct, the bug is fixed. Otherwise the game will crash inside the Amiga. Unfortunately, this is hard to debug. I had to play for about 3 minutes until the emulator crashed.

**Comment by dirkwhoffmann** [comment] 2019-07-19 13:41
When I replace the assert() by a call to debug(), I can see in the debug log that the game writes to address 0:  

    [6533] (258, 44)  030610 BCB--A 4038 07C0 Blitter: bltdpt = 0

Interestingly, the game does not crash, so the write to 0 is intentional.

Therefore the crash can be fixed by simply removing the assert().

However, I run into another bug later in the game: 

    [9564] (247,186)  06E080 BCB--A 4038 07C0 Memory: WARNING: peek16(729FD): Address violation error (reading odd address)

I'll still close this issue, because the memory violation (wherever it comes from) is hardly impossible to debug with this game. Memory violations of this kind are usually secondary effects that have a completely different root cause.

Although there are lots of bugs left, I still can't believe that we are already debugging games (the emulator is just 7 month old. A baby emulator so to speak).

**Closed** 2019-07-19 13:43 UTC

**Comment by mithrendal** [comment] 2019-07-19 13:46
baby emulator spawned from Amiga genetics ! ;-)

**Comment by dirkwhoffmann** [comment] 2019-07-19 13:56
> spawned from Amiga genetics

I really hope we do not need a license for what we're doing 😬, Germany is a bit hypersensitive when it comes to genetic research. On the other hand... we all know what happened in Jurassic Park. It all started with a cute little baby dino, if I remember correctly 😳.
