### ISSUE TITLE
Lemon - Groovy: Missing white line

### ISSUE THREAD

**Issue by emoon** [dirkwhoffmann/vAmiga#391] opened 2020-07-25 15:53 UTC
https://demozoo.org/productions/169 - http://ftp.amigascne.org/pub/amiga/Groups/L/Lemon/LEMON-Groovy.DMS

At 1:20 there should be a white line on the left side of this box in the middle as seen here http://www.youtube.com/watch?v=B2DT-n6p9c8&t=1m20s In vAmiga it's missing

![000](https://user-images.githubusercontent.com/350822/88460839-900b4100-ce9f-11ea-8b4b-819b064f2901.png)

**Comment by dirkwhoffmann** [comment] 2020-07-26 14:03
The patient goes to X-ray... please hold on 😷.

<img width="927" alt="Bildschirmfoto 2020-07-26 um 15 40 55" src="https://user-images.githubusercontent.com/12561945/88480594-15056180-cf57-11ea-90ef-e3792e6c0e01.png">

As we can clearly see, the patient is suffering from a particularly severe form of "Copper" 🤒. Copper activity (yellow) is all over the place. 

Let's view it without the Copper...

<img width="927" alt="Bildschirmfoto 2020-07-26 um 15 43 56" src="https://user-images.githubusercontent.com/12561945/88480626-3cf4c500-cf57-11ea-8735-66cd659e7e92.png">

In addition to hiding Copper DMA, I removed all sprite layers. The result is fascinating. The playfield only covers two third of the rectangle. The right part is covered partly by sprites. Between the sprites, there is still something to see, but there is no bitplane DMA going on. And there is no sprite DMA in these lines. This means that either the DMA debugger went crazy (unlikely) or the sprite and bitplane data registers are filled manually in this area. This would explain the heavy Copper load 🤔. 

How in the world shall I debug this? 🙈

**Comment by emoon** [comment] 2020-07-26 15:11
Might be worth looking at the DMA debugger in UAE to see how it differs?

**Comment by emoon** [comment] 2020-07-28 13:29
I have an idea what this can be. It's possible with the copper to repeat sprites (example here https://codetapper.com/amiga/sprite-tricks/risky-woods) and as there are no bitplanes enabled maybe that is the case here.

**Comment by tonioni** [comment] 2020-07-28 16:44
I think this is the case where sprites can be horizontally visible 1 lores pixel before first possible visible bitplane pixel. Very annoying hardware feature to emulate..

**Comment by emoon** [comment] 2020-07-28 17:31
But I think bitplanes is fully disabled in this case. Does that still happen then?

**Comment by dirkwhoffmann** [comment] 2020-07-28 17:39
> I think this is the case where sprites can be horizontally visible 1 lores pixel before first possible visible bitplane pixe

In theory, vAmiga should be able to handle this. There are special tests in Sprites/clip for this: 

![clip1_A500_8A](https://user-images.githubusercontent.com/12561945/88701075-d663d880-d109-11ea-906a-57ea51c1c657.JPG)

**Comment by dirkwhoffmann** [comment] 2020-09-29 13:32
Fixed in v0.9.12 😎

<img width="899" alt="Bildschirmfoto 2020-09-29 um 15 21 49" src="https://user-images.githubusercontent.com/12561945/94564801-b5824580-0268-11eb-9e60-a087ef017894.png">

**Closed by dirkwhoffmann** 2020-09-29 13:32 UTC
Labels: Demo, bug

**Comment by emoon** [comment] 2020-09-29 15:37
nice! fixed by https://github.com/dirkwhoffmann/vAmiga/commit/644af8547ce81bfad898d8c16480a57a716b3db0 ?

**Comment by dirkwhoffmann** [comment] 2020-09-29 15:53
>  fixed by 644af85 ?

I didn't verify which checkin actually fixed it (didn't run the demo for a while), but I share your guess. I think it was likely caused by the Line Blitter issue. BTW, this was a really stupid cut-and-paste style bug. I applied a pointer mask to a boolean instead of testing it for zero. I hope this piece of code didn't find it's way into the Arctic preservation project 🙈.

**Comment by emoon** [comment] 2020-09-29 15:57
haha :)
