### ISSUE TITLE
Freddy Is Back by Paradox has glitching graphics

### ISSUE THREAD

**Issue by emoon** [dirkwhoffmann/vAmiga#487] opened 2021-04-17 15:55 UTC
This https://www.pouet.net/prod.php?which=11125 has some glitching graphics as seen in these screenshots. Tested with vAmiga 0.9.18.1

![003](https://user-images.githubusercontent.com/350822/115118916-fe4fe080-9fa5-11eb-9e67-e3955430cfec.png)
![004](https://user-images.githubusercontent.com/350822/115118922-03ad2b00-9fa6-11eb-8852-b150255389d7.png)

**Comment by dirkwhoffmann** [comment] 2021-04-18 17:06
This one should be resolved with the next release (it's a duplicate of #485, I think).

I've recorded a small sequence with the latest code which appears to be glitch-free:
https://dirkwhoffmann.github.io/vAmiga/videos/ParadoxDemo.mov

**Comment by dirkwhoffmann** [comment] 2021-04-20 14:42
Fixed in v1.0b1

**Closed by dirkwhoffmann** 2021-04-20 14:42 UTC
Labels: Bug, duplicate
