### ISSUE TITLE
The curious case of Chamber of Shaolin (Grandslam 1989).

### ISSUE THREAD

**Issue by Gianmarco72** [dirkwhoffmann/vAmiga#339] opened 2020-05-12 16:45 UTC
Strange behavior: during the title screen to continue you need to press the space bar, but if the "Joystick Keyset 1" emulation is active nothing happens (I think there's priority to the fire button). Disabling the emulation it works. I think it's not a bug.

In addition, sometimes the game doesn't continue to load after the title screen "The Grandslam" appears:
<img width="868" alt="Schermata 2020-05-12 alle 17 52 43" src="https://user-images.githubusercontent.com/45571833/81719972-0f32d080-947e-11ea-9b29-59d24e86b783.png">
... and after a few seconds vAmiga crashes.

**Comment by dirkwhoffmann** [comment] 2020-05-20 12:36
I haven't experienced a crash in v0.9.7 yet, but I can confirm the other issue. There is also a problem after inserting the second disk. The game constantly moves the head between track 0 and track 40 on the second disk, but doesn't load. 

> I think there's priority to the fire button

Yes, by default, all keys used for device emulation are invisible to the keyboard handler. This feature can be switched off here: 

<img width="758" alt="Bildschirmfoto 2020-05-20 um 14 27 25" src="https://user-images.githubusercontent.com/12561945/82446320-bcbd6980-9aa6-11ea-849b-2a5d2f0d8020.png">

**Comment by Gianmarco72** [comment] 2020-05-20 15:28
> Yes, by default, all keys used for device emulation are invisible to the keyboard handler. This feature can be switched off here:

Great!! 👍🏻

**Comment by dirkwhoffmann** [comment] 2020-05-24 16:53
> The game constantly moves the head between track 0 and track 40 on the second disk, but doesn't load.

I just verified that this also happens in UAE, so I guess the game is broken (or at least the second disk is).

> In addition, sometimes the game doesn't continue to load

This happens in UAE, too, from time to time. There was even a cool effect where the screen went blood red with fancy moving stripes and audio got crazy. But just before I was able to take a picture, it turned black and froze.

> ... and after a few seconds vAmiga crashes.

The crash seems to be gone. Since the two other issues are most likely not to be blamed on the emulator, I'll close this issue for now...

**Closed by dirkwhoffmann** 2020-05-24 16:53 UTC
Labels: Game, bug
