### ISSUE TITLE
Game behaves very erratic on the Mac version, while on vAmigaweb it is smooth

### ISSUE THREAD

**Issue by rhinoid** [dirkwhoffmann/vAmiga#760] opened 2022-11-24 09:47 UTC
When running my old game on the Mac the framerate is all over the place which makes playing the game very tricky.
Strangely enough, when running the web version of vAmiga the framerate does seem more constant.
Mac used:  2019 Macbook pro.   Game used:  2 disk game Hoi. If you want I can attach it to this thread.

**Comment by rhinoid** [comment] 2022-11-24 09:49
Ah my apologies if this issue conflicts with the beta vsync feature I'm just reading about as an open issue.

**Comment by dirkwhoffmann** [comment] 2022-11-24 11:29
My first guess would be that warp mode kicks in during disk transfers. VSYNC wouldn't cause such behavior.

**Comment by rhinoid** [comment] 2022-11-24 12:07
Warp is turned off and I'm sure there is no disk activity while the game runs.
When I look at it it most resembles that every few frames it stops rendering a handful of frames and then renders again. Which makes for the stuttery experience. Maybe it tries to keep up but is just on the edge of what is possible?

**Comment by dirkwhoffmann** [comment] 2022-11-24 12:22
> Warp is turned off and I'm sure there is no disk activity while the game runs.

Hmm, OK. Could you post a screenshot and the exact name of the ADF you're using? Please don't post the ADF itself. I'll have a look at it.

**Comment by rhinoid** [comment] 2022-11-24 12:39
Cool. It's available on archive.org undder the name: "Hoi (Let's Play!) Amiga game"
It's a 2 disker but only uses Df0 so at some point you need to swap. 

In any case, as soon as level1 starts (the green dragon next to his shoe) it should already be apparent what I'm talking about.
Let me know if this is enough info to get you there.   Thanks!

**Comment by dirkwhoffmann** [comment] 2022-11-24 12:51
>  It's available on archive.org undder the name: "Hoi (Let's Play!) Amiga game"

Thanks, got it.

The emulator runs in warp mode, because the game doesn't turn off the drive motor which is indicated by the green drive led in the status bar (normally, the led is grey). The debugger shows all details: 

<img width="952" alt="Bildschirm­foto 2022-11-24 um 13 42 31" src="https://user-images.githubusercontent.com/12561945/203788378-c1257094-d801-45fc-95e8-50e6fa59c6c0.png">

You can alter this behavior either in the preferences or by clicking the hourglass icon in the status bar: 

<img width="839" alt="Bildschirm­foto 2022-11-24 um 13 43 10" src="https://user-images.githubusercontent.com/12561945/203788520-060baaa1-604d-4ea4-825d-83ff71a1dd61.png">

**Comment by mithrendal** [comment] 2022-11-24 13:15
The same reason why we couldn’t enable warp during disk load in vAmigaWeb in https://github.com/vAmigaWeb/vAmigaWeb/issues/137

**Comment by rhinoid** [comment] 2022-11-24 14:26
Thats weird,  in my version (Version 2.1 (220812)) the preferences says: Warp mode activation "Never".
And in the bottom right corner I see not an hourglass but a lock:
<img width="493" alt="Screenshot 2022-11-24 at 15 25 17" src="https://user-images.githubusercontent.com/2438289/203807538-2e35f3e4-28f1-4142-8e09-9edab394534c.png">
And yet I have the stuttering... Should I be on a later version?

**Comment by mithrendal** [comment] 2022-11-24 14:31
left to the lock it shows the warp speed comparable to Mhz... i.e. if constantly 7.01 then warp is off. Could you tell us what you see for numbers ?

**Comment by dirkwhoffmann** [comment] 2022-11-24 14:37
> And yet I have the stuttering... Should I be on a later version?

No, version 2.1 is fine. 

It works flawlessly here (great game, btw!!). I guess it must be something machine specific. 

https://user-images.githubusercontent.com/12561945/203809520-6f2660f6-0f82-4f55-b514-dbf44c0519a7.mov

**Comment by dirkwhoffmann** [comment] 2022-11-24 14:42
What CPU load do you get on your machine while the game is running? To display the CPU load, click on the marked icon in the status bar. 

<img width="952" alt="Bildschirm­foto 2022-11-24 um 15 38 16" src="https://user-images.githubusercontent.com/12561945/203810346-169a8889-65ed-44fe-9db7-ceba6844ce95.png">

**Comment by mithrendal** [comment] 2022-11-24 14:44
It is so hard to let it catch the banana and not to let it die ... I finally managed it 😎... you have to jump in a very flat angle to the left.... in my opinion it should be awarded by more than the 50 points 🤓...

**Comment by rhinoid** [comment] 2022-11-24 14:51
https://user-images.githubusercontent.com/2438289/203812199-99f14030-276c-4d2d-91e8-fd0f826a89ae.mp4

Attached is a screencapture of the mac itself (cmd-shift-5) and then handbraking it (ffmpeg frontend) to get it a bit smaller in size. The stutters are quite visible in it. As is the processor power needed (around 20%).

(haha yes I don't know if it is even possible to collect every fruit. The goal however is to collect the black diamonds. (Or just get to the end of the level))

**Comment by dirkwhoffmann** [comment] 2022-12-23 13:26
I'm closing the issue for now, because I am not able to reproduce it (hence, I don't know how to debug it).

**Closed by dirkwhoffmann** 2022-12-23 13:26 UTC
Labels: Needs investigation
