### ISSUE TITLE
Times of Lore intro graphic error

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#225] opened 2019-11-10 09:17 UTC
Hi, there is a graph error in the intro of this game, the info screen are cutted at bottom:

[Times of Lore (1988)(Origin)[cr PNA].adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3828258/Times.of.Lore.1988.Origin.cr.PNA.adf.zip)

<img width="780" alt="Schermata 2019-11-10 alle 10 09 29" src="https://user-images.githubusercontent.com/34916641/68541706-4e834600-03a3-11ea-9fd7-6c8989f31b46.png">
<img width="771" alt="Schermata 2019-11-10 alle 10 07 55" src="https://user-images.githubusercontent.com/34916641/68541707-5216cd00-03a3-11ea-8e6e-f216eb41baad.png">

**Comment by dirkwhoffmann** [comment] 2019-11-10 14:10
As usual, let's x-ray the patient first. Graphics seems to stop around a line where the Copper becomes active. Hence, we've got out first suspect.

<img width="872" alt="Bildschirmfoto 2019-11-10 um 14 56 50" src="https://user-images.githubusercontent.com/12561945/68545211-2c9db980-03cb-11ea-9249-1cbbbce0eea8.png">

Let's see what our suspect is doing here... 

OMG 🤭

<img width="980" alt="Bildschirmfoto 2019-11-10 um 14 59 12" src="https://user-images.githubusercontent.com/12561945/68545238-6f5f9180-03cb-11ea-967f-ddaecdc69ff7.png">



As you can see, the issue occurs in line $FF where (besides other stuff), an interrupt is triggered.

Oh no, it's interrupts again 🙈.

**Comment by dirkwhoffmann** [comment] 2020-01-15 15:29
Update: Same in v0.55. Not related to interrupts.

**Comment by dirkwhoffmann** [comment] 2020-02-02 08:33
Coming closer.

<img width="910" alt="Bildschirmfoto 2020-02-02 um 09 24 49" src="https://user-images.githubusercontent.com/12561945/73605460-cc1fb200-459e-11ea-9a38-095df23fa6f6.png">

The first red line marks line $AF. According to the Copper list, this is where the IRQ gets triggered. The second red line marks $FF. At this line, color registers 2 to 15 are supposed to be set to black. In vAmiga, the second wait seems to be ignored and the color registers are changed to black around line $AF. Thus, the image seems to be cropped, but it is simply drawn in black from this point on. The DMA debugger view backs this hypothesis. As can be seen in the cyan DMA stripes, bitplane data is still being transferred. Unfortunately, I haven't been able to reproduce the issue in an isolated test case yet.

**Comment by dirkwhoffmann** [comment] 2020-02-02 09:40
Fixed in v0.57.2 (needs OCS Agnus)

<img width="910" alt="Bildschirmfoto 2020-02-02 um 10 31 24" src="https://user-images.githubusercontent.com/12561945/73606203-515b9480-45a8-11ea-85ab-149bb44f0eb7.png">

**Closed by dirkwhoffmann** 2020-02-02 09:40 UTC
Labels: Copper, Game, Priority-High, bug
