### ISSUE TITLE
Soldier of Light has some graph errors

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#126] opened 2019-08-13 09:10 UTC
Soldier of Light has some graph error in the menu game as shown below and during the game has the same problem of Black lamp I think because if I make a screenshot the graphic problem during the game is not shown.

[Soldier of Light (1988)(Softek)[t +2 AFL].adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3496205/Soldier.of.Light.1988.Softek.t.%2B2.AFL.adf.zip)

<img width="857" alt="Schermata 2019-08-13 alle 11 06 23" src="https://user-images.githubusercontent.com/34916641/62929498-e67c8e00-bdba-11e9-9f4f-a5a3e7de2746.png">

**Comment by dirkwhoffmann** [comment] 2019-08-13 15:19
Let's look at the Copper list first:

<img width="980" alt="Bildschirmfoto 2019-08-13 um 17 03 42" src="https://user-images.githubusercontent.com/12561945/62952925-ded5dd00-bdec-11e9-83c7-1605fda9236c.png">

The games has a very simple Copper list. What you can't see on the still image is that the bitplane pointers are changing all the time. This means that the CPU is modifying the Copper list on-the-fly. The bug is possibly due to some race condition between the CPU and the Copper.

There is Blitter activity, too, but I can confirm that it works in SAE with the "Immediate" Blitter.

<img width="746" alt="Bildschirmfoto 2019-08-13 um 17 15 47" src="https://user-images.githubusercontent.com/12561945/62953638-2c067e80-bdee-11e9-886a-fa3b68ac5b06.png">

🤔 Strange

**Comment by Alessandro1970** [comment] 2019-09-01 08:07
In v3 with blitter accuracy 2 and 3 there are graphic erros in this page of the game Soldier of Light (strange but better with blitter accuracy 0)
<img width="805" alt="Schermata 2019-09-01 alle 10 05 20" src="https://user-images.githubusercontent.com/34916641/64073566-479fcf00-cca0-11e9-956b-82e0cf9db7b2.png">

**Comment by dirkwhoffmann** [comment] 2019-09-01 08:12
That's a great test case!!!

It'll help to debug the bus allocation issues in Blitter level 1 and 2.

When writing the SlowBlitter, I've learned that the crucial part is not the cycle-accurate execution of the internal Blitter components, but the cycle-accurate usage of the bus. I think vAmiga has issues running the CPU and the Blitter side by side when the Blitter nasty bit is 0. In this case, both share the bus by some time-slicing mechanism.

**Comment by dirkwhoffmann** [comment] 2019-10-04 11:46
> In v3 with blitter accuracy 2 and 3 there are graphic erros in this page of the game

Hmmm, just verified it on the real machine. For me, it looks the same: 

![IMG_1967](https://user-images.githubusercontent.com/12561945/66204801-fb371d00-e6ab-11e9-8fc3-e5850725a957.jpeg)

Overall, the game is very sensitive to Blitter timing though. The next screen draws well in (the current version of) vAmiga, if Blitter accuracy is set to 2.

<img width="828" alt="Bildschirmfoto 2019-10-04 um 13 28 34" src="https://user-images.githubusercontent.com/12561945/66204891-46e9c680-e6ac-11e9-8375-144036fa5105.png">

![IMG_1968](https://user-images.githubusercontent.com/12561945/66204902-4ea96b00-e6ac-11e9-9dd8-58e6050994d6.jpeg)

It flickers in vAmiga if the Fast Blitter is utilised. In SAE, the screen is cropped in that case.

The game itself does show some graphics glitches in vAmiga (even if Blitter accuracy is set to 2).

**Comment by Alessandro1970** [comment] 2019-11-04 22:15
In 0.45 works fine with blitter accuracy 2
<img width="781" alt="Schermata 2019-11-04 alle 23 14 10" src="https://user-images.githubusercontent.com/34916641/68162712-f094cf80-ff58-11e9-84f8-1f7b453f9324.png">
<img width="781" alt="Schermata 2019-11-04 alle 23 14 26" src="https://user-images.githubusercontent.com/34916641/68162715-f4285680-ff58-11e9-994c-59b73ded38c2.png">

**Comment by dirkwhoffmann** [comment] 2019-11-05 06:49
First of all, this is great news!

There is another issue though: 

1. Start the game until the intro with the blue stripe comes up (works well first time)
2. Hit Reset. The intro won't come up again. It'll stop here:

![Bildschirmfoto 2019-11-05 um 07 42 13](https://user-images.githubusercontent.com/12561945/68184764-3de85f80-ffa0-11e9-8e07-971a9d070080.png)

There is an error message dumped to serial out:

![Bildschirmfoto 2019-11-05 um 07 42 09](https://user-images.githubusercontent.com/12561945/68184793-493b8b00-ffa0-11e9-99a0-3636ddc52090.png)

It must have something to do with uninitialized variables or the way, the reset vector is grabbed. I need to look through all my components and check the reset / initialization code.

**Comment by dirkwhoffmann** [comment] 2019-11-14 11:27
Couldn't reproduce the "broken after reset" issue in v0.46.1. I'll close it for now.

**Closed by dirkwhoffmann** 2019-11-14 11:27 UTC
Labels: Blitter, bug
