### ISSUE TITLE
Phenomena Hard 'n' Heavy Intro

### ISSUE THREAD

**Issue by chris70c** [dirkwhoffmann/vAmiga#578] opened 2021-10-26 03:07 UTC
Below the logo to the left there is some white pixels garbage scrolling in from time to time, also the dots behind the guy when they scroll to the right they're cut off, doesn't happens in WinUAE.

![vamiga](https://user-images.githubusercontent.com/3858768/138802230-33544316-099d-42a2-a93e-81ecb7472b2c.png)
[Hard n Heavy (Phenomena).zip](https://github.com/dirkwhoffmann/vAmiga/files/7414830/Hard.n.Heavy.Phenomena.zip)

**Comment by dirkwhoffmann** [comment] 2021-11-06 10:42
Confirmed. Runs flawlessly on my A500 8A. No pixel garbage, no cutoff.

**Comment by dirkwhoffmann** [comment] 2021-11-08 15:24
Here is a comparison of a scene between UAE and vAmiga:

<img width="833" alt="Bildschirmfoto 2021-11-08 um 16 03 38" src="https://user-images.githubusercontent.com/12561945/140766477-6ae7028c-08d5-49f0-9592-93e824c8dbec.png">

<img width="1024" alt="Bildschirmfoto 2021-11-08 um 16 03 43" src="https://user-images.githubusercontent.com/12561945/140766499-a20812f6-d98c-41ae-84b4-fc88f3b2101f.png">

Findings:
- The guy is positioned correctly.
- In vAmiga, the star field is shifted to the right.

X-ray (with Blitter DMA disabled because it is all over the place):

<img width="1024" alt="Bildschirmfoto 2021-11-08 um 15 50 37" src="https://user-images.githubusercontent.com/12561945/140768348-53a63231-0fa5-456a-8d03-6bb3d68a8a3e.png">

Interestingly, there are no sprites involved and the entire scene is single playfield. The Copper activity at the right (yellow arrow) writes different values into BPLCON1 to shift the bitplanes. This moves the star field.

There is some suspicious bitplane DMA in the line marked with the red arrow. DMA starts at the position of the line above and ends at the position of the line below.

**Comment by dirkwhoffmann** [comment] 2022-01-21 18:02
I'm still in the middle of reworking the entire bitplane sequencer logic in Agnus (DDF, DIWV etc.). Although the new code is not ready for production yet, it already fixes the star field issue:

<img width="666" alt="Bildschirmfoto 2022-01-21 um 18 57 22" src="https://user-images.githubusercontent.com/12561945/150576921-dd559822-f19f-4612-8767-17babb23b80f.png">

**Comment by dirkwhoffmann** [comment] 2022-01-23 20:15
Fixed in v1.1b8

**Closed by dirkwhoffmann** 2022-01-23 20:15 UTC
Labels: Bug, V1.1
