### ISSUE TITLE
vAmiga 0.9.17.1 crashes reproducibly by "Use as Default"

### ISSUE THREAD

**Issue by lotlorien** [dirkwhoffmann/vAmiga#474] opened 2021-02-22 10:35 UTC
Hello, I found that whenever I drag a Kickstart Rom in the "Kickstart Rom or Boot Rom" place (this works fine) and then click on "Use as Default" the emulator crashes. vAmiga 0.9.17.1, BigSur 11.2.1, Intel Mac. The workaround is to drag the Rom in everytime you start the emulator and then just click on Power.

**Comment by dirkwhoffmann** [comment] 2021-02-22 10:46
Thanks for reporting! This is most likely a duplicate of #469.

**Closed** 2021-03-03 17:05 UTC
Labels: Bug
